# Generated by Django 5.0 on 2024-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
